### ISSUE TITLE
Sugerencia para participar en el Hacktoberfest

### ISSUE THREAD

**Issue by eisenheimjelid** [python-la-paz/pyeventos#21]
¡Hola! Comunidad de Python La Paz,

> _When Hacktoberfest started in 2014, 676 participants showed up to contribute. In 2023, nearly 98,000 people participated._

Hacktoberfest es un evento que dura todo el mes de octubre, año con año, en esta 11ª edición para 2024, promueven la difusión y colaboración del código abierto (open source). La participación en el mundo del software no es necesariamente solo con código, se pueden hacer contribuciones en temas legales, traducciones, documentación, reporte de fallas y pruebas.

La propuesta es que la comunidad decida si quiere o no participar en este evento. Si bien, es un poco controversial por los intereses privados en los que se ve envuelto el evento gracias a los patrocinadores; pero el espíritu de contribuir al open-source es un interés legítimo que podrían compartir en su comunidad.

La propuesta concreta es seguir los lineamientos del evento en: <https://hacktoberfest.com/participation/#maintainers> para cumplir con los requisitos y llevar `pyeventos`, o cualquier otro proyecto de la comunidad, a un público mucho más amplio.

**Comment by taicoding** [comment]
Hola @eisenheimjelid agradecemos mucho tu sugerencia, nos encantaria poder ser parte del **hacktoberfest** con este proyecto,  sin embargo el proyecto aun esta en una etapa temprana de socializacion. Tenemos planeado al año poder ser parte del **hacktoberfest** lo que implica ir redactando issues y tomando notas de las sugerencias y el feedback que logremos recibir en esta etapa de socializacion. 😄 🐍 

Muchas gracias por tu interes en el proyecto, tu sugerencia es muy valiosa y queda anotada 😸
